domain: larsrose.github.com/
url: larsrose.github.com/autonomia
baseurl: "/"

title: Work in progress
email: github.comautonomia.sphere466@passmail.net
author: Lars

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
